# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SCH_Accumulation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SCH_Accumulation

  target 'SCH_AccumulationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SCH_AccumulationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
