platform :ios, '9.0'

target 'SCH_Accumulation' do
  pod 'AFNetworking', :inhibit_warnings => true
  pod 'MJExtension', :inhibit_warnings => true
  pod 'SDWebImage', :inhibit_warnings => true
  pod 'MJRefresh', :inhibit_warnings => true
  pod 'Masonry', :inhibit_warnings => true

  target 'SCH_AccumulationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SCH_AccumulationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
